package polygon.models;

public class Financial extends DateFinancial {
    public String ticker;
    public String period;
    public String calendarDate;
    public String reportPeriod;
    public String updated;
    public String dateKey;
    public double accumulatedOtherComprehensiveIncome;
    public double assets;
    public double assetsAverage;
    public double assetsCurrent;
    public double assetTurnover;
    public double assetsNonCurrent;
    public double bookValuePerShare;
    public double capitalExpenditure;
    public double cashAndEquivalents;
    public double cashAndEquivalentsUSD;
    public double costOfRevenue;
    public double consolidatedIncome;
    public double currentRatio;
    public double debtToEquityRatio;
    public double debt;
    public double debtCurrent;
    public double debtNonCurrent;
    public double debtUSD;
    public double deferredRevenue;
    public double depreciationAmortizationAndAccretion;
    public double deposits;
    public double dividendYield;
    public double dividendsPerBasicCommonShare;
    public double earningBeforeInterestTaxes;
    public double earningsBeforeInterestTaxesDepreciationAmortization;
    public double EBITDAMargin;
    public double earningsBeforeInterestTaxesDepreciationAmortizationUSD;
    public double earningBeforeInterestTaxesUSD;
    public double earningsBeforeTax;
    public double earningsPerBasicShare;
    public double earningsPerDilutedShare;
    public double earningsPerBasicShareUSD;
    public double shareholdersEquity;
    public double averageEquity;
    public double shareholdersEquityUSD;
    public double enterpriseValue;
    public double enterpriseValueOverEBIT;
    public double enterpriseValueOverEBITDA;
    public double freeCashFlow;
    public double freeCashFlowPerShare;
    public double foreignCurrencyUSDExchangeRate;
    public double grossProfit;
    public double grossMargin;
    public double goodwillAndIntangibleAssets;
    public double interestExpense;
    public double investedCapital;
    public double investedCapitalAverage;
    public double inventory;
    public double investments;
    public double investmentsCurrent;
    public double investmentsNonCurrent;
    public double totalLiabilities;
    public double currentLiabilities;
    public double liabilitiesNonCurrent;
    public double marketCapitalization;
    public double netCashFlow;
    public double netCashFlowBusinessAcquisitionsDisposals;
    public double issuanceEquityShares;
    public double issuanceDebtSecurities;
    public double paymentDividendsOtherCashDistributions;
    public double netCashFlowFromFinancing;
    public double netCashFlowFromInvesting;
    public double netCashFlowInvestmentAcquisitionsDisposals;
    public double netCashFlowFromOperations;
    public double effectOfExchangeRateChangesOnCash;
    public double netIncome;
    public double netIncomeCommonStock;
    public double netIncomeCommonStockUSD;
    public double netLossIncomeFromDiscontinuedOperations;
    public double netIncomeToNonControllingInterests;
    public double profitMargin;
    public double operatingExpenses;
    public double operatingIncome;
    public double tradeAndNonTradePayables;
    public double payoutRatio;
    public double priceToBookValue;
    public double priceEarnings;
    public double priceToEarningsRatio;
    public double propertyPlantEquipmentNet;
    public double preferredDividendsIncomeStatementImpact;
    public double sharePriceAdjustedClose;
    public double priceSales;
    public double priceToSalesRatio;
    public double tradeAndNonTradeReceivables;
    public double accumulatedRetainedEarningsDeficit;
    public double revenues;
    public double revenuesUSD;
    public double researchAndDevelopmentExpense;
    public double returnOnAverageAssets;
    public double returnOnAverageEquity;
    public double returnOnInvestedCapital;
    public double returnOnSales;
    public double shareBasedCompensation;
    public double sellingGeneralAndAdministrativeExpense;
    public double shareFactor;
    public double shares;
    public double weightedAverageShares;
    public double weightedAverageSharesDiluted;
    public double salesPerShare;
    public double tangibleAssetValue;
    public double taxAssets;
    public double incomeTaxExpense;
    public double taxLiabilities;
    public double tangibleAssetsBookValuePerShare;
    public double workingCapital;

    @Override
    public String getDateString() {
        return dateKey;
    }

    @Override
    public String getTicker() {
        return ticker;
    }
}
