package polygon.models;

public class Financial extends DateFinancial {
    public String dateKey;
    public String ticker;
    public String period;
    public String calendarDate;
    public String reportPeriod;
    public String updated;
    public Double accumulatedOtherComprehensiveIncome;
    public Double assets;
    public Double assetsAverage;
    public Double assetsCurrent;
    public Double assetTurnover;
    public Double assetsNonCurrent;
    public Double bookValuePerShare;
    public Double capitalExpenditure;
    public Double cashAndEquivalents;
    public Double cashAndEquivalentsUSD;
    public Double costOfRevenue;
    public Double consolidatedIncome;
    public Double currentRatio;
    public Double debtToEquityRatio;
    public Double debt;
    public Double debtCurrent;
    public Double debtNonCurrent;
    public Double debtUSD;
    public Double deferredRevenue;
    public Double depreciationAmortizationAndAccretion;
    public Double deposits;
    public Double dividendYield;
    public Double dividendsPerBasicCommonShare;
    public Double earningBeforeInterestTaxes;
    public Double earningsBeforeInterestTaxesDepreciationAmortization;
    public Double EBITDAMargin;
    public Double earningsBeforeInterestTaxesDepreciationAmortizationUSD;
    public Double earningBeforeInterestTaxesUSD;
    public Double earningsBeforeTax;
    public Double earningsPerBasicShare;
    public Double earningsPerDilutedShare;
    public Double earningsPerBasicShareUSD;
    public Double shareholdersEquity;
    public Double averageEquity;
    public Double shareholdersEquityUSD;
    public Double enterpriseValue;
    public Double enterpriseValueOverEBIT;
    public Double enterpriseValueOverEBITDA;
    public Double freeCashFlow;
    public Double freeCashFlowPerShare;
    public Double foreignCurrencyUSDExchangeRate;
    public Double grossProfit;
    public Double grossMargin;
    public Double goodwillAndIntangibleAssets;
    public Double interestExpense;
    public Double investedCapital;
    public Double investedCapitalAverage;
    public Double inventory;
    public Double investments;
    public Double investmentsCurrent;
    public Double investmentsNonCurrent;
    public Double totalLiabilities;
    public Double currentLiabilities;
    public Double liabilitiesNonCurrent;
    public Double marketCapitalization;
    public Double netCashFlow;
    public Double netCashFlowBusinessAcquisitionsDisposals;
    public Double issuanceEquityShares;
    public Double issuanceDebtSecurities;
    public Double paymentDividendsOtherCashDistributions;
    public Double netCashFlowFromFinancing;
    public Double netCashFlowFromInvesting;
    public Double netCashFlowInvestmentAcquisitionsDisposals;
    public Double netCashFlowFromOperations;
    public Double effectOfExchangeRateChangesOnCash;
    public Double netIncome;
    public Double netIncomeCommonStock;
    public Double netIncomeCommonStockUSD;
    public Double netLossIncomeFromDiscontinuedOperations;
    public Double netIncomeToNonControllingInterests;
    public Double profitMargin;
    public Double operatingExpenses;
    public Double operatingIncome;
    public Double tradeAndNonTradePayables;
    public Double payoutRatio;
    public Double priceToBookValue;
    public Double priceEarnings;
    public Double priceToEarningsRatio;
    public Double propertyPlantEquipmentNet;
    public Double preferredDividendsIncomeStatementImpact;
    public Double sharePriceAdjustedClose;
    public Double priceSales;
    public Double priceToSalesRatio;
    public Double tradeAndNonTradeReceivables;
    public Double accumulatedRetainedEarningsDeficit;
    public Double revenues;
    public Double revenuesUSD;
    public Double researchAndDevelopmentExpense;
    public Double returnOnAverageAssets;
    public Double returnOnAverageEquity;
    public Double returnOnInvestedCapital;
    public Double returnOnSales;
    public Double shareBasedCompensation;
    public Double sellingGeneralAndAdministrativeExpense;
    public Double shareFactor;
    public Double shares;
    public Double weightedAverageShares;
    public Double weightedAverageSharesDiluted;
    public Double salesPerShare;
    public Double tangibleAssetValue;
    public Double taxAssets;
    public Double incomeTaxExpense;
    public Double taxLiabilities;
    public Double tangibleAssetsBookValuePerShare;
    public Double workingCapital;

    @Override
    public String getDateString() {
        return dateKey;
    }

    @Override
    public String getTicker() {
        return ticker;
    }
}
